### ISSUE TITLE
Support passing url to AsyncAPI file

### ISSUE THREAD

**Issue by derberg** [asyncapi/cli#7]
#### Reason/Context

The initial version of CLI that we soon merge in supports files from the file system. We should support remote files as parser and generator already support it. 

#### Description
- User passes `--context` as `https://raw.githubusercontent.com/asyncapi/asyncapi/master/examples/2.0.0/simple.yml`.
- Even though the parser has `parseFromURL` option, it doesn't mean that all tools in the figure will support it from day 1. For example, the diff library doesn't have to include any dependency to `fetch` to pull spec from the remote. This means we need to have independent functionality that fetches the spec from remote if we detect that context points to URL

**Comment by Souvikns** [comment]
Here I would like to clarify something, 

When the user sets the context he then does not have to pass in the async API spec path for other commands, so context is like a global setting for the CLI. 
So my question is when the user sets the context how do we persist it? If we store the spec path or the URL in the local file system then when happens when the CLI is installed globally and the user is using it for multiple projects.

**Comment by derberg** [comment]
context should be optional, and I still should be able to pass context with a flag in case I'm doing some automation, or working with multiple files.

context should also be smart in the way that if I do not have context set, and I do not pass `--context` command, CLI check if there are files called `asyncapi.json/yml/yaml` in workdir, and picks them up.

context should most probably be persisted in a file.

**Comment by Souvikns** [comment]
Will it help if CLI parses both the local file and the URL and provides the parsed spec object for other tools to use.

**Comment by derberg** [comment]
I'm closing this one, it is a bit outdated looking at what we already have better have new issue

**Comment by Souvikns** [comment]
So I read how this is implemented in `generator`. As of now, we are storing the local path to the spec in the context from where we are loading the current context as a result we do not need to pass the file path every time as an argument. 

So to support the loading spec file from the URL, we have to consider two options. 
- `--url` parameter, and also update the `useSpecFile` hook that will be used by other commands in the future. 
- Check and persist URL as a context value, For this we need to update the `contextService` and also `SpecificationFile` class. But the question arises should we persist URL in context because if we check an URL and it is working fine but in the future, the URL might not work as intended and then that stored context is wrong.

**Comment by magicmatatjahu** [comment]
@Souvikns Rather than adding additional flag like `--url`, I suggest that we should change the `--file` flag to the `--spec` flag which will support both file path and url.

About your concerns:

> Check and persist URL as a context value, For this we need to update the contextService and also SpecificationFile class. 

`SpecificationFile` implements [this](https://github.com/asyncapi/cli/blob/master/src/hooks/validation/models.ts#L4) interface, so for url, we should create separate class `SpecificationUrl`. 

> But the question that arises should we persist URL in context because if we check an URL and it is working fine but in the future, the URL might not work as intended and then that stored context is wrong

In this same way, you can change the path of the file from current context and context won't work.

I'm wondering if we should download the spec from URL every time or just once and add a flag for re-downloading. We can have a discussion about that.

For me we should go for the `--spec` flag, but we can wait for the Łukasz, because there should be more that one voice - he will be back in the Monday :)

Whichever flag we choose, we should have in mind that someone would like to define options for downloading, perhaps similar to those in curl, or (which is better) allow passing as `--spec` also normal string, so then someone can have possibility to concatenate curl with our cli like:

```bash
asyncapi validate --spec ${curl ...}
```

so we will use the output from curl. What do you think? :)

**Comment by fmvilas** [comment]
I've seen the discussion in #1 and gonna reply here so we move the conversation to this issue. I'd not use the `--spec` option because the "spec" is AsyncAPI and the file is a **document**. I think there's a base problem with this approach we're taking on the CLI. We're "abusing" options (those starting with `--` or `-`) for mandatory things. When something is mandatory, it shouldn't be an option because, as the name implies, they're optional.

**Comment by fmvilas** [comment]
So I think it should be something like:

```
asyncapi validate <asyncapi-file-or-url>
```

It's easy to detect if the argument `asyncapi-file-or-url` is a URL or a file.

**Comment by Souvikns** [comment]
@fmvilas after persisting the context, we are able to intelligently pick up the spec path according to the `current set context` or by autodetecting any spec file from the working directory so `asyncapi validate` will automatically pick up the spec file and validate. So thus I was using the flag to override the initial choice. 
Then if we have `specfile path or url` as input then should still keep the context as a flag or take that as an input as well. `context-key-file-path-or-url`.

**Comment by fmvilas** [comment]
Alright, I see what you mean. I think this "context" thing is gonna bite us hard in the future 😄 But it's not related to this issue so nevermind.

**Comment by magicmatatjahu** [comment]
We merged PR with `--file` so quickly, my fault 😅  Probably we should rethinking the way of passing doc to the CLI.

Currently we have feature called context, where we persist the (currently only local file) document of AsyncAPI and we can perform action on that. However, overriding current doc for the given command should be also available, and by this we have `--file` flag. Passing the file path/url/content of doc as argument (not as flag) like in our generator is very handy. We must also have in mind that in the future we will handle command for the multiple files, like `asyncapi diff` to check difference between two specs. And here is a problem: how to handle context and the another spec given as input? Context should persist only one spec, so the we will end probably with:

```
asyncapi diff <file-to-doc>
```

and then doc on which we will perform diff will be fetched from current spec...

So maybe going with flags, we should extend idea from @fmvilas and treat arguments as doc(s) using the format `{context|doc}:{path/url/value}` so we will end with:

- using current context:

  ```bash
  asyncapi validate
  ```
  
- using doc from given context:

  ```bash
  asyncapi validate context:custom-context
  ```
  
- using doc from file/url:

  ```bash
  asyncapi validate doc:./path/to/file.yaml
  ```
  
- using value as input

  ```bash
  asyncapi validate doc:${curl ...}
  ```
  
- using multiple arguments (perform diff on doc from context and from file):

  ```bash
  asyncapi diff context:custom-context doc:./path/to/file.yaml
  ```
  
We can make this also by flags, but in this solution we treat doc as primary citizen of our CLI.

**Comment by derberg** [comment]
@magicmatatjahu we had initial discusison on CLI here https://github.com/asyncapi/cli/issues/1 and idea where AsyncAPI document is in the center got "dropped" for now. Btw, I also do not think approach with `:` us too intuitive. 

btw, I closed this issue because of `I'm closing this one, it is a bit outdated looking at what we already have better have new issue` as the description is really super old and not matching current state of CLI, only confuses others.

file is a file, no matter if on local or remote, so no matter if `./asyncapi.yml` or `http://my.com/asyncapi.yml`, these are still files. And it is a flag as it is optional, not mandatory, as you can have default context set +  CLI looks for standard files names in CWD.

**Comment by magicmatatjahu** [comment]
@derberg Ok, I agree with your point of view, however my first thought is that `--file` points to the local file, not remote, so for that I suggested `--spec` or `--doc`.  

> And it is a flag as it is optional, not mandatory, as you can have default context set 

Exactly, I know about that but I also wanted to put myself in the user's shoes and see if `--file` has a good UX and check if standalone arguments would be better.

**Comment by derberg** [comment]
I agree with @fmvilas that `spec` is not a good word as we do not talk about spec here. And `doc` is not bad, I just think `file` is pretty neutral. When we talk about AsyncAPIs created by users, we talk about files and documents, but I think more common is talking about AsyncAPI file, as document always has this close relation to documentation, and we know AsyncAPI is more than that. I suggest we stay with `file` and in future I don't see a problem we add multiple names for the same option if larger group of users is confused

**Comment by fmvilas** [comment]
🤔 I'm not sure I get it. I still see a clash between path and context name:

```
asyncapi validate my_app
```

Is `my_app` a context name or a file path? What if it's an existing file but the user really wanted to use the `my_app` context?

> you can differentiate, we just assume that file path is valid only if points to file with extension (. is there)

What prevents someone from using a context name with a dot (`.`)?

> And we can always do fallback, check first context and then file, or file and then context

Yeah, I was assuming we do some fallback but the problem persists when the provided name is **both** an existing context name and a file.

**Comment by derberg** [comment]
First of all what is the probability that someone has a context with dot in a name, and that the context name is `my_app.yml`. So the risk is there but imho it is ok to accept that risk in favour of better DX. With a proper fallback strategy, it will work fine. We can have `-- debug` flag that can log more info on what is exactly happening and what was picked up. But as a response from validation and in future other commands you always get a path to the file that was processed, so easy to pick by the user what was used.

**Comment by fmvilas** [comment]
Alright, let's accept this theoretically low risk and learn from real usage data 👍

**Comment by derberg** [comment]
yup, in the end, CLI is still not at 1.0 release, we are breaking commands and options all the time now 😄
